### ISSUE TITLE
Déployer la plateforme de staging

### ISSUE THREAD

**Issue by tut-tuuut** [betagouv/gestion-des-subventions-locales#13]
```[tasklist]
### Tasks
- [ ] Création de l'app scalingo gsl-staging
- [ ] Création du NDD
- [ ] Déploiement du code sur l'app scalingo
- [ ] Vérification
```
